### ISSUE TITLE
[TypeError: Cannot read property 'match' of null] on SRT's with multi-line captions

### ISSUE THREAD

**Issue by eceasy** [gsantiago/subtitle.js#10]
Running this code the following throws the type error on [this file](http://www.filedropper.com/subtitles_1)
```
srt = fs.readFileSync(join(__dirname, subtitlePath), 'utf8');
            try {
                _subtitle = new Subtitle(srt);
            }
            catch (e) {
                console.log(e);
            }

```
I suspect the issue starts after subtitle 373 of the given srt, where the captions take up multiple lines and whitespace. I tried parse everything before that, and it works fine.

**Comment by gsantiago** [comment]
That's exactly the problem.

When a new blank line is found, the program will interpret this as a new subtitle and expects the timestamp patterns. 

I don't know if this is a problem with the subtitle.js itself, or it is the subtitles.srt file that is incorrectly.

**Comment by gsantiago** [comment]
Since there are no official SRT specs, I used this source:
https://matroska.org/technical/specs/subtitles/srt.html

It says that a blank line indicates the start of a new subtitle.

**Comment by gsantiago** [comment]
Since there are no official SRT specs, I used this source:
https://matroska.org/technical/specs/subtitles/srt.html

It says that a blank line indicates the start of a new subtitle.

**Comment by eceasy** [comment]
It doesn't necessarily say every blank line indicates a new subtitle, but that a blank line will indicate one. But I see your point and this is a pretty rare edge case, so I'll close this.

**Comment by gsantiago** [comment]
Did you try execute this subtitles.srt file in a player?

**Comment by eceasy** [comment]
It's extracted from a mkv file that had working subtitles.

**Comment by gsantiago** [comment]
I have tried it in SMPlayer and it looks like the .srt is indeed invalid.

Thanks!
