### ISSUE TITLE
TypeError: Cannot read property 'match' of null on working SRT file

### ISSUE THREAD

**Issue by eceasy** [gsantiago/subtitle.js#11]
[SRT here](http://www.filedropper.com/ffflovelive-02bd720p-aaca4adba3b)
Using the same code as before. I've tested playing the SRT in VLC and it works fine. There doesn't seem to be any multi-line captions.
```
            srt = fs.readFileSync(join(__dirname, srtPath), 'utf8');
            try {
                _subtitle = new Subtitle(srt);
            }
            catch (e) {
                reject(e);
            }
```

**Comment by gsantiago** [comment]
Actually there is a blank line at row 7332:

```
1829
00:11:31,920 --> 00:11:33,170
<font face="Yryr minc R" size="50" color="#696663"><b>{\an5}<font size="16">Kanda Shrine

Otoko-zaka Entrance</font></b></font>
```

Can you try to run VLC in this particular timestamp and see what happens?

Thank you!

**Comment by eceasy** [comment]
Sorry for the late reply. Just tested it, the bottom line doesn't appear. This seems to be a pretty common issue from what I've seen though.
