### ISSUE TITLE
Add support to ES6 modules

### ISSUE THREAD

**Issue by hector** [gsantiago/subtitle.js#18]
I am trying to do:
```javascript
import { parse } from 'subtitle';
```
but it doesn't work.

Update: I am doing this inside a project created with "creare-react-app", so I am using webpack and all the whistles.

**Comment by gsantiago** [comment]
@hector It doesn't support ES6 modules yet.

You can do this:

```js
const { parse } = require('subtitle')
```

Or import the whole module:

```js
import subtitle from 'subtitle'
subtitle.parse('...')
```

But thanks for your issue. I will add support to ES6 modules soon :+1:

**Comment by hector** [comment]
That you be great @gsantiago :)
