### ISSUE TITLE
Browser Build 1.0.1 returns an empty object

### ISSUE THREAD

**Issue by chrislim** [gsantiago/subtitle.js#19]
Hello, when I try to load the browser versions of the library, all I get is an empty Subtitle object. Looking at the built code in 5e79d023 it looks like between 1.0.0 and 1.0.1 the body of the module was lost. Could you update the built browser files? Thanks!

**Comment by gsantiago** [comment]
Thanks for your feedback. This is related to #18 and I plan to fix it soon.

**Comment by gsantiago** [comment]
Fixed
