### ISSUE TITLE
Drop syntactically wrong subtitle lines

### ISSUE THREAD

**Issue by r4ndr4s4** [gsantiago/subtitle.js#27]
Drop syntactically wrong subtitle lines instead of throwing exception when parsing them. I'm building a web application based on this module, and sometimes I got wrong .srt files from OpenSubtitles.org.

## Example:

[Mad.Men.S03E03.My.Old.Kentucky.Home.HDTV.XviD-FQM.srt in English](https://dl.opensubtitles.org/en/download/src-api/vrf-19a80c55/sid-VuD1YbsDmah,BMHPRkfm6Q0T70d/filead/1952238194.srt)

597
00:00:0,500 --> 00:00:2,00
<font color="#ffff00" size=14>www.tvsubtitles.net</font>

**Comment by gsantiago** [comment]
I think that an option called `skipInvalidCaptions` would be a good feature and solve your issue.

It could be something like this:

```js
parse(srt, {
  skipInvalidCaptions: true
})
```

Then, it wouldn't throw any exception.

What do you think?

**Comment by r4ndr4s4** [comment]
It would be great, thanks!
