### ISSUE TITLE
How to make this work?

### ISSUE THREAD

**Issue by zettam** [gsantiago/subtitle.js#3]
Can't seem to make it work constantly getting the error "has no method 'replace'"
Any examples would be nice!

**Comment by gsantiago** [comment]
Hi @zettam, thanks for open an issue.

Could you show more details of this error and what are you trying to do?

It looks like you are not passing a string value to the `parse` method.

Try to do something like that:

```javascript
var mySRT = 'contents of your SRT here...';

var captions = new Subtitle();

// pass the SRT content to the `parse` method
captions.parse(mySRT);

// get an object
captions.getSubtitles();
```

Also, I recommend you to run the tests.

Run: ```npm test``` to check if the script is running ok in your system.

**Comment by zettam** [comment]
"contents of your srt here" part - I'm unable to handle it.
I tried streaming the file via fs to the variable, but I believe I failed.

Can you send a quick example that reads the file? I believe that's where I'm doing my mistake

Cheers

**Comment by gsantiago** [comment]
Try to do something like that:

```javascript
srt = fs.readFileSync('yourFile.srt', 'utf8');
captions.parse(srt.toString());
```

**Comment by zettam** [comment]
```  var match = time.match(/^(\d{2}):(\d{2}):(\d{2}),(\d{3})$/);
                   ^
TypeError: Cannot call method 'match' of undefined
    at Function.Subtitle.toMS (C:\nodetests\srtread\node_modules\subtitle\subtitle.js:153:20)
    at C:\nodetests\srtread\node_modules\subtitle\subtitle.js:78:28
    at Array.forEach (native)
    at Subtitle.parse (C:\nodetests\srtread\node_modules\subtitle\subtitle.js:50:7)
    at Object.<anonymous> (C:\nodetests\srtread\subbie.js:10:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)```

**Comment by gsantiago** [comment]
Did you try run the tests by running 'npm test'?

Well, could you show your whole code?

**Comment by zettam** [comment]
var fs = require('fs-extra')
    var Subtitle = require('subtitle');
    var captions = new Subtitle();
    srt = fs.readFileSync('Kingsman.The.Secret.Service.2014.720p.BluRay.x264.YIFY_eng.srt', 'utf8');
    captions.parse(srt.toString());

no I will do the test now

**Comment by gsantiago** [comment]
Did you check the srt's content?

Try put it in a console.log to see its contents.

console.log(srt);

Also, check out its type.

console.log(typeof srt);

**Comment by zettam** [comment]
typeof -> string
console log works.

I tried this with many srt's (not only this one) - same result

**Comment by gsantiago** [comment]
What about the tests?

Install Mocha globally. 'npm install mocha -g'

Go to subtitle's folder in node_modules.

Run: 'mocha'

See if the result is ok or some cases fail.

In the tests, I also import a .srt file using the fs module.

**Comment by zettam** [comment]
I don't know how to make tests, honestly.
Can you guide me there?
Checking mocha now.

**Comment by gsantiago** [comment]
It's simple to test.

After install Mocha, just go to subtitle's directory in node_modules.

Run: 'mocha'

Show the messages.

**Comment by zettam** [comment]
![mocha](https://cloud.githubusercontent.com/assets/2744905/7798592/6831fe2e-0304-11e5-86d0-a951a11cbc08.PNG)
 mocha result

**Comment by gsantiago** [comment]
In the subtitle's folder, run: 'npm install' to install all dev dependencies.

After that, try Mocha again.

**Comment by zettam** [comment]
![mocha](https://cloud.githubusercontent.com/assets/2744905/7798613/a4ea8854-0304-11e5-84f4-f4066807fa06.PNG)
New result

**Comment by gsantiago** [comment]
Well, it looks there aren't any problem with subtitle.js.

**Comment by gsantiago** [comment]
I will send an example later.

**Comment by zettam** [comment]
Hm what can be the issue then?

**Comment by zettam** [comment]
I'm unable to find a solution.

**Comment by zettam** [comment]
Any help is greatly appreciated.

**Comment by gsantiago** [comment]
I've just pushed an example. It works fine.

https://github.com/gsantiago/subtitle.js/tree/master/examples

**Comment by zettam** [comment]
subtitle\subtitle.js:153
var match = time.match(/^(\d{2}):(\d{2}):(\d{2}),(\d{3})$/);

TypeError: Cannot call method 'match' of undefined

**Comment by gsantiago** [comment]
Did my example throw this error?

**Comment by zettam** [comment]
yes

**Comment by gsantiago** [comment]
That's weird. It runs perfect here.

What's your Node's version?

**Comment by zettam** [comment]
Final version

**Comment by gsantiago** [comment]
Well, the problem isn't the subtitle.js and I don't know how to help you.

**Comment by gsantiago** [comment]
Sorry, @zettam.
The problem was with subtitle.js

Update the package and try run the script again.
