### ISSUE TITLE
parse vtt or srt fails with 1-digit hour 

### ISSUE THREAD

**Issue by HaithemMosbahi** [gsantiago/subtitle.js#31]
First of all, thank you for this library it really saved me lot of time. However, I had an issue with the parse module and I believe it's a bug.
So I tried to parse a vtt content using the parse function and it failed because of this line even though it's a valid WebVTT format : 
   `1:04:09.717 --> 1:04:12.886`

I did an investigation and I found out that the regular expression used to parse the time expects 2 digits for Hours. I think this could be fixed in the library by adjusting the regular expression to accept Hours with 1 or 2 digits.

I would be happy to help and create a pull request for this bug.

**Comment by gsantiago** [comment]
Thanks for your contribution!

Of course, you can send a PR. Also, it would be nice if you could include some tests.

**Comment by gsantiago** [comment]
Fixed by #45 and published as version 2.0.4
