### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by jenglamlow** [gsantiago/subtitle.js#33]
Hi,

Is there any plan to support Typescript by providing declaration file? I have check "@types/subtitle" is not exist yet in NPM yet

**Comment by gsantiago** [comment]
I'm open for contributions

**Comment by jenglamlow** [comment]
I have created a definition file and create PR to DefinitelyTyped repo. It is successfully merged https://github.com/DefinitelyTyped/DefinitelyTyped/commit/e33c890af636f35f98bf8f66834af8f058ba2d8f 

You should get to download the definition file at `@types/subtitle` soon

**Comment by gsantiago** [comment]
Where do I get this file? Do I need to commit it or publish it on npm?

**Comment by jenglamlow** [comment]
Hi,

You can get the file at [here](https://www.npmjs.com/package/@types/subtitle)

I'm closing this issue
