### ISSUE TITLE
problem with Internet explorer

### ISSUE THREAD

**Issue by xtoolkit** [gsantiago/subtitle.js#35]
hi
subtitle.js problem in Internet Explorers
![image](https://user-images.githubusercontent.com/8210666/48966447-eba86b80-efe6-11e8-8a64-2c1f05b18d6a.png)
please fix this

**Comment by gsantiago** [comment]
You can include a polyfill to include support for Object.assign method

- https://www.npmjs.com/package/es6-object-assign
