### ISSUE TITLE
Not transpiled `module` entry in `package.json` overrides `main`

### ISSUE THREAD

**Issue by tomaas-zeman** [gsantiago/subtitle.js#39]
Hi, we just hit an issue that might be relevant for everyone 

https://github.com/gsantiago/subtitle.js/commit/edf0581387b746e921f683e86ea40d290685e1de

The change introduces a new field in `package.json` which unfortunately overrides the older `main` entrypoint. The result is that webpack (that is not configured to transpile `node_modules`) includes code from `lib` (not transpiled), instead of `dist/subtitle.bundle.js`

**Comment by gsantiago** [comment]
How could we fix that?

**Comment by tomaas-zeman** [comment]
It depends... What was the reason for making that change in the first place? Do you need to have ES6 code for `module` entrypoint or not?
