### ISSUE TITLE
Lookup by timecode?

### ISSUE THREAD

**Issue by RWOverdijk** [gsantiago/subtitle.js#42]
Perhaps a silly question, perhaps not. Let's find out 😄

This library works exactly as it says, for which my thanks. Right now I'm trying to not only read the file, but also pick out a specific subtitle based on a timecode. Is there anything provided by this library for that? Or will I have to build something myself/find a different library for that part?

I'm building my own player, but it's not based on video so I can't really use those solutions. I'm parsing the subtitle files for "playing" myself, but need a good way to find the proper subtitles at a given timestamp.

In any case, thank you for this library.

**Comment by aneesijaz** [comment]
Well seems it returns the start and end time in milliseconds you will just have to match it with the correct time (currentTime) via find method...
just subscribe to the video ontimeupdate event and do.
Something like
`let currentCue = Subtitle.parse(xhr.responseText ).find(s => s.start == (myVideElement.currentTime / 1000))`

**Comment by RWOverdijk** [comment]
Yeah, I wrote something myself that's a bit better for performance. Thanks anyway :)
