### ISSUE TITLE
Add support for identifers

### ISSUE THREAD

**Issue by gsantiago** [gsantiago/subtitle.js#61]
Currently, this module has not support for identifiers. It would be interesting to add support to identifiers like the examples below:

## webvtt

```
WEBVTT

1 - Some ID here
00:00:22.230 --> 00:00:24.606
This is the first subtitle.
```

The caption above would be parsed to this:

```js
{
    id: '1 - Some ID here',
    start: 20000,
    end: 24400,
    text: 'This is the first subtitle'
  },
```

The stringify should support this feature too.

**Comment by danielsfirnaciuc** [comment]
Hi @gsantiago 
any news on this little fellow? :)

**Comment by gsantiago** [comment]
@danielsfirnaciuc nothing yet
