### ISSUE TITLE
Support single digit timestamps

### ISSUE THREAD

**Issue by nbarnett** [gsantiago/subtitle.js#81]
Following on from https://github.com/gsantiago/subtitle.js/issues/31, I'd like to also support having single digits for minutes, seconds, and milliseconds values rather than only supporting hours. Although the [WebVTT spec](https://www.w3.org/TR/webvtt1/#webvtt-timestamp) requires timestamps to include leading and trailing zeroes (e.g. 00:00:00.000), I've seen some tools that do VTT export (most notably Microsoft Teams) not adhere to this (e.g. 0:0:0.0) which unfortunately causes parsing to fail entirely.

It would be nice to be able to gracefully handle files like this rather than failing to parse. 

I would be happy to submit a PR to make this change.

**Comment by gsantiago** [comment]
Published as 4.2.0 version. Thanks!
